# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
notifications:
  slack:
    secure: h98/AS/nZwgILbsb8xoHdnheIXTrZyRvGnW1+jGw84TURLCu0o6AEqMDRYtBMWPHigeNbBJG4/JVFHRPHM/bey0iOSQ5rKxR+2skpT/kvavLLXUczny8eNexbdwETxy8crnUFXdkKEz+1DJBGLOeaYGxTvSuowsLtI1pp6OWvJXJQuivmEkEjD6WqgdhOLC0NlQrXRwo0XLldggW0PQQa6xW4LzMKGet7/1WZWyB3LcX5ecK+gCZ0DB6QKxUB+p0425Fc1xOSTIXdXprMRFj8ilaVNNPcjXgjNJHeOg6e2UvUbGKyCeg1m+bBryGPU3cSCF2PVG2KMvw9Lw7AtDfs4ADptbi97owQG43KEyvDKHOrn6qdWBxEKlJiyENDYni2Q/qy2SHvXm7cKxUeToPDtvLgoFhw8+MjwAfUpKyLcXj3bBvz6RKTbXZKOlSWBkH8r9PMpOWoAr0r8/MwFSKjXHNAWaKsJeML+UpjMjqH8ZRZbk/StI4CrGPWrENMOcTkTFiicbdwcOFsRE+/y6mNGJ3yddXmkPs6iA94GC+Gj3gqMlfe386Rh20lqG2ni8ZqLGASTsfuxVmDvc22m+q+vshecbsYFoWs4gzgdpIugin5oleMfhc79NVNKyZyzZfhz/EAn7bBXLvLNjm1o8JAenL1HroIuGxFoQOUCidQKY=
